name: task-api-test
services:
  server:
    build:
      context: "."
      target: base
    command: "./scripts/wait-for-it.sh database:5432 -- ./scripts/test-cmd.sh"
    environment:
      PRISMA_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - 30001:3000
    volumes:
      - ./src:/api/src
      - ./package.json:/api/package.json
    networks:
      - test_vm
    depends_on:
      - database
  database:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - test_vm
volumes:
  database:
networks:
  test_vm:
