name: task-api-dev
services:
  server:
    build:
      context: "."
      target: base
    command: npm run dev
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/api/src
      - ./package.json:/api/package.json
    networks:
      - dev_vm
    depends_on:
      - database
  database:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    expose:
      - 54320
    ports:
      - 54320:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - dev_vm
volumes:
  database:
networks:
  dev_vm:
